#
# Vivado (TM) v2016.4 (64-bit)
#
# redpitaya.tcl: Tcl script for re-creating project 'redpitaya'
#
# Generated by Vivado on Fri Mar 06 18:11:40 +0100 2020
# IP Build 1755317 on Mon Jan 23 20:30:07 MST 2017
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (redpitaya.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "lithpulser_package.vhd"
#    "lithpulser_outddr.vhd"
#    "lithpulser_mux.vhd"
#    "lithpulser_matcher.vhd"
#    "lithpulser.vhd"
#    "redpitaya/redpitaya.vhd"
#    "redpitaya/system.bd"
#    "sdc/red_pitaya.xdc"
#    "sim/lithpulser_mux_tb.vhd"
#    "sim/lithpulser_matcher_tb.vhd"
#    "sim/lithpulser_outddr_tb.vhd"
#    "sim/lithpulser_mux_tb_behav.wcfg"
#    "sim/lithpulser_outddr_tb_behav.wcfg"
#    "sim/lithpulser_matcher_tb_behav.wcfg"
#    "sim/lithpulser_tb.vhd"
#    "sim/lithpulser_tb_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "redpitaya.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/redpitaya_build"]"

# Create project
create_project redpitaya_build ./redpitaya_build -part xc7z010clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects redpitaya_build]
set_property "corecontainer.enable" "1" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "disable" $obj
set_property "part" "xc7z010clg400-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/lithpulser_package.vhd"]"\
 "[file normalize "$origin_dir/lithpulser_outddr.vhd"]"\
 "[file normalize "$origin_dir/lithpulser_mux.vhd"]"\
 "[file normalize "$origin_dir/lithpulser_matcher.vhd"]"\
 "[file normalize "$origin_dir/lithpulser.vhd"]"\
 "[file normalize "$origin_dir/redpitaya/redpitaya_hk.vhd"]"\
 "[file normalize "$origin_dir/redpitaya/system.bd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "lithpulser_package.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "lithpulser_outddr.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "lithpulser_mux.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "lithpulser_matcher.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "lithpulser.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "redpitaya/redpitaya_hk.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "redpitaya/system.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}
set_property "used_in" "synthesis implementation" $file_obj
set_property "used_in_simulation" "0" $file_obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/sdc/red_pitaya.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "sdc/red_pitaya.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/sdc/red_pitaya.xdc"]" $obj

# Create 'components' fileset (if not found)
if {[string equal [get_filesets -quiet components] ""]} {
  create_fileset -simset components
}

# Set 'componets' fileset object
set obj [get_filesets components]
set files [list \
 "[file normalize "$origin_dir/sim/lithpulser_mux_tb.vhd"]"\
 "[file normalize "$origin_dir/sim/lithpulser_matcher_tb.vhd"]"\
 "[file normalize "$origin_dir/sim/lithpulser_outddr_tb.vhd"]"\
 "[file normalize "$origin_dir/sim/lithpulser_mux_tb_behav.wcfg"]"\
 "[file normalize "$origin_dir/sim/lithpulser_outddr_tb_behav.wcfg"]"\
 "[file normalize "$origin_dir/sim/lithpulser_matcher_tb_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'components' fileset file properties for remote files
# None

# Set 'components' fileset file properties for local files
set file "sim/lithpulser_mux_tb.vhd"
set file_obj [get_files -of_objects [get_filesets components] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "sim/lithpulser_matcher_tb.vhd"
set file_obj [get_files -of_objects [get_filesets components] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "sim/lithpulser_outddr_tb.vhd"
set file_obj [get_files -of_objects [get_filesets components] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj


# Set 'components' fileset properties
set obj [get_filesets components]
set_property "top" "lithpulser_mux_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.rangecheck" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.view" "sim/lithpulser_mux_tb_behav.wcfg sim/lithpulser_outddr_tb_behav.wcfg sim/lithpulser_matcher_tb_behav.wcfg" $obj

# Create 'main' fileset (if not found)
if {[string equal [get_filesets -quiet main] ""]} {
  create_fileset -simset main
}

# Set 'main' fileset object
set obj [get_filesets main]
set files [list \
 "[file normalize "$origin_dir/sim/lithpulser_tb.vhd"]"\
 "[file normalize "$origin_dir/sim/lithpulser_tb_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'main' fileset file properties for remote files
# None

# Set 'main' fileset file properties for local files
set file "sim/lithpulser_tb.vhd"
set file_obj [get_files -of_objects [get_filesets main] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_synthesis" "0" $file_obj


# Set 'main' fileset properties
set obj [get_filesets main]
set_property "runtime" "10us" $obj
set_property "top" "lithpulser_tb" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.rangecheck" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.elaborate.rangecheck" "1" $obj
set_property "xsim.simulate.runtime" "10us" $obj
set_property "xsim.view" "sim/lithpulser_tb_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z010clg400-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z010clg400-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z010clg400-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z010clg400-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj
set_property "steps.write_bitstream.args.bin_file" true $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:redpitaya_build"

update_ip_catalog -rebuild -scan_changes

make_wrapper -files [get_files redpitaya/system.bd] -top
add_files -norecurse redpitaya/hdl/system_wrapper.vhd
set_property top system_wrapper [current_fileset]

current_fileset -simset [ get_filesets main ]


















